CREATE TABLE appusers(
id BIGINT NOT NULL auto_increment,
fullname VARCHAR(60) NOT NULL,
email VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(20) NOT NULL,
role VARCHAR (10) NOT NULL,
PRIMARY KEY(id)
);