CREATE TABLE appusers(
id BIGINT NOT NULL auto_increment,
full_name VARCHAR(60) NOT NULL,
email VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(70) NOT NULL,
user_role VARCHAR (10) NOT NULL,
PRIMARY KEY(id)
);