spring:
  application:
    name: Tarefator
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${TAREFATOR_DATABASE_URL}
      username: ${TAREFATOR_DATABASE_USERNAME}
      password: ${TAREFATOR_DATABASE_PASSWORD}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    time-zone: America/Sao_Paulo
